const testChilds = [
  {
      "_id": "qxwj4x0oye2lvlik2v8mr",
      "name": "SCHEDULE 1",
      "type": "FILE",
      "fileID": "YaoaDjLBqmufx1wX",
      "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
      "childFile": true,
      "parentFileId": "Dpcd9UcAW8wd6sFF",
      "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
  },
  {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "SCHEDULE 2",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wE",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
     "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "SCHEDULE 3",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "SCHEDULE 4",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "SCHEDULE 5",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "Agreement Of Sales",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "apple",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "Hello World",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "Loan Agreement 1",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "Loan Agreement 2",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "Loan Agreement 3",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
    {
        "_id": "qxwj4x0oye2lvlik2v8mr",
        "name": "Payment Instructions",
        "type": "FILE",
        "fileID": "YaoaDjLBqmufx1wX",
        "projectID": "vzHQt2ohbPs2M2mwHky0flezLrkeJZjV",
        "childFile": true,
        "parentFileId": "Dpcd9UcAW8wd6sFF",
        "userID": "grvOSOVgW7YQotHYGSJpBVwQvOE2",
    },
]
export default testChilds;